import React,{useEffect,useRef,useState}from'react';

const uid=()=>Math.random().toString(36).slice(2,9);
function App(){
 const [clips,setClips]=useState([]),[active,setActive]=useState(0),[text,setText]=useState(''),[textSize,setTextSize]=useState(48),[textColor,setTextColor]=useState('#ffffff'),[pos,setPos]=useState('bottom'),[playing,setPlaying]=useState(false),[exporting,setExporting]=useState(false),[progress,setProgress]=useState(0),[ratio,setRatio]=useState('16:9'),[error,setError]=useState('');
 const video=useRef(),canvas=useRef(),fileInput=useRef(),raf=useRef(),music=useRef(),audioCtx=useRef(),mixDest=useRef(),videoSource=useRef(),musicSource=useRef();
 const addFiles=files=>{const arr=[...files].filter(f=>f.type.startsWith('video/')).map(file=>({id:uid(),file,url:URL.createObjectURL(file),name:file.name,start:0,end:null,duration:0}));if(!arr.length){setError('Pilih file video MP4, WebM, MOV, atau format yang didukung browser.');return}setClips(c=>{const n=[...c,...arr];if(!c.length)setActive(0);return n});setError('')};
 useEffect(()=>()=>clips.forEach(c=>URL.revokeObjectURL(c.url)),[]);
 useEffect(()=>{const v=video.current,c=clips[active];if(!v||!c)return;v.src=c.url;v.currentTime=c.start;v.load();const ready=()=>setClips(x=>x.map((q,i)=>i===active?{...q,duration:v.duration,end:q.end??v.duration}:q));v.addEventListener('loadedmetadata',ready);return()=>v.removeEventListener('loadedmetadata',ready)},[active,clips.length]);
 const updateClip=(key,val)=>setClips(x=>x.map((c,i)=>i===active?{...c,[key]:Math.max(0,Number(val))}:c));
 const remove=()=>{setClips(x=>{const n=x.filter((_,i)=>i!==active);setActive(Math.max(0,Math.min(active,n.length-1)));return n})};
 const move=(d)=>setClips(x=>{const n=[...x],j=active+d;if(j<0||j>=n.length)return n;[n[active],n[j]]=[n[j],n[active]];setActive(j);return n});
 const draw=()=>{const c=canvas.current,v=video.current;if(!c||!v)return;const [rw,rh]=ratio.split(':').map(Number),W=1280,H=Math.round(1280*rh/rw);c.width=W;c.height=H;const scale=Math.max(W/v.videoWidth,H/v.videoHeight);const w=v.videoWidth*scale,h=v.videoHeight*scale;c.getContext('2d').fillStyle='#000';c.getContext('2d').fillRect(0,0,W,H);c.getContext('2d').drawImage(v,(W-w)/2,(H-h)/2,w,h);if(text){const x=W/2;const y=pos==='top'?90:pos==='center'?H/2:H-90;const ctx=c.getContext('2d');ctx.font=`700 ${textSize}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineWidth=8;ctx.strokeStyle='rgba(0,0,0,.7)';ctx.strokeText(text,x,y);ctx.fillStyle=textColor;ctx.fillText(text,x,y)}};
 const loop=()=>{draw();if(playing)raf.current=requestAnimationFrame(loop)};
 useEffect(()=>{if(playing)loop();return()=>cancelAnimationFrame(raf.current)},[playing,text,textSize,textColor,pos,ratio,active]);
 const toggle=()=>{if(!video.current)return;if(playing){video.current.pause();setPlaying(false)}else{video.current.play();setPlaying(true)}};
 const exportVideo=async()=>{if(!clips.length)return;setExporting(true);setProgress(0);setError('');try{const c=canvas.current,v=video.current;if(!audioCtx.current){audioCtx.current=new AudioContext();mixDest.current=audioCtx.current.createMediaStreamDestination();videoSource.current=audioCtx.current.createMediaElementSource(v);videoSource.current.connect(mixDest.current);videoSource.current.connect(audioCtx.current.destination);if(music.current){musicSource.current=audioCtx.current.createMediaElementSource(music.current);musicSource.current.connect(mixDest.current)}}await audioCtx.current.resume();const stream=c.captureStream(30);mixDest.current.stream.getAudioTracks().forEach(t=>stream.addTrack(t));const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus')?'video/webm;codecs=vp9,opus':'video/webm';const rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:8000000});const chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);const done=new Promise(r=>rec.onstop=r);rec.start(250);for(let i=0;i<clips.length;i++){setActive(i);await new Promise(r=>setTimeout(r,80));const q=clips[i];v.currentTime=q.start;await v.play();setPlaying(true);await new Promise(resolve=>{const tick=()=>{draw();setProgress(Math.round(((i+(v.currentTime-q.start)/Math.max(.01,(q.end??v.duration)-q.start))/clips.length)*100));if(v.currentTime>=(q.end??v.duration)-.03){v.pause();resolve()}else requestAnimationFrame(tick)};tick()});}setPlaying(false);rec.stop();await done;const blob=new Blob(chunks,{type:mime}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='video-maker-export.webm';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}catch(e){console.error(e);setError('Export gagal di browser ini. Coba Chrome/Edge terbaru dan pastikan video dapat diputar.')}finally{setExporting(false);setProgress(0)}};
 return <div className="vm"><header><div className="brand"><span>▶</span><div><b>Video Maker Pro</b><small>Browser Video Editor</small></div></div><div className="actions"><button onClick={()=>fileInput.current.click()}>＋ Tambah Video</button><button className="primary" disabled={!clips.length||exporting} onClick={exportVideo}>{exporting?`Export ${progress}%`:'Export Video'}</button><input ref={fileInput} hidden type="file" accept="video/*" multiple onChange={e=>addFiles(e.target.files)}/></div></header>
 <main><aside className="media"><h3>Media</h3>{clips.length?<div className="cliplist">{clips.map((c,i)=><div className={'mediaitem '+(i===active?'sel':'')} onClick={()=>setActive(i)} key={c.id}><video src={c.url}/><span>{i+1}. {c.name}</span></div>)}</div>:<div className="drop" onClick={()=>fileInput.current.click()}>📁<strong>Tambahkan video</strong><small>MP4 / WebM / MOV</small></div>}</aside>
 <section className="workspace"><div className="preview"><video ref={video} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onTimeUpdate={()=>{draw();const q=clips[active];if(q&&q.end&&video.currentTime>=q.end){video.currentTime=q.end;video.currentTime=q.start}}}/><canvas ref={canvas}/><div className="previewtext">{text}</div></div><div className="controls"><button onClick={()=>video.current&&(video.current.currentTime=Math.max(0,video.current.currentTime-.1))}>−0.1s</button><button className="play" onClick={toggle}>{playing?'❚❚':'▶'}</button><button onClick={()=>video.current&&(video.current.currentTime+=.1)}>+0.1s</button><select value={ratio} onChange={e=>setRatio(e.target.value)}><option value="16:9">16:9</option><option value="9:16">9:16</option><option value="1:1">1:1</option><option value="4:5">4:5</option></select></div>
 <div className="timeline"><div className="track">{clips.map((c,i)=><div key={c.id} className={'tlclip '+(i===active?'active':'')} style={{width:`${Math.max(12,(c.duration||5)*12)}%`}} onClick={()=>setActive(i)}>{c.name}</div>)}</div><div className="timelinebar">{clips.length?`${clips.length} klip • durasi dapat dipotong`: 'Belum ada klip'}</div></div></section>
 <aside className="properties"><h3>Inspector</h3>{clips.length?<><label>Trim mulai (detik)<input type="number" min="0" step="0.1" value={clips[active]?.start||0} onChange={e=>updateClip('start',e.target.value)}/></label><label>Trim akhir (detik)<input type="number" min="0" step="0.1" value={clips[active]?.end??clips[active]?.duration||0} onChange={e=>updateClip('end',e.target.value)}/></label><hr/><label>Rasio<select value={ratio} onChange={e=>setRatio(e.target.value)}><option>16:9</option><option>9:16</option><option>1:1</option><option>4:5</option></select></label><label>Text overlay<input value={text} onChange={e=>setText(e.target.value)} placeholder="Judul video..."/></label><label>Ukuran teks<input type="range" min="20" max="120" value={textSize} onChange={e=>setTextSize(+e.target.value)}/></label><label>Warna teks<input type="color" value={textColor} onChange={e=>setTextColor(e.target.value)}/></label><label>Posisi<select value={pos} onChange={e=>setPos(e.target.value)}><option value="top">Atas</option><option value="center">Tengah</option><option value="bottom">Bawah</option></select></label><hr/><button className="danger" onClick={remove}>Hapus klip</button><div className="move"><button onClick={()=>move(-1)}>←</button><button onClick={()=>move(1)}>→</button></div></>:<p className="hint">Pilih video untuk mengedit.</p>}<label className="music">Musik background<input type="file" accept="audio/*" onChange={e=>{const f=e.target.files[0];if(f){music.current.src=URL.createObjectURL(f);music.current.loop=true;music.current.play().catch(()=>{})}}}/></label><audio ref={music} controls/></aside></main>{error&&<div className="error">{error}</div>}<footer>Semua proses utama berjalan di browser Anda • Tidak perlu upload video ke server</footer></div>}
export default App;
